-- "Nderro": customers part-exchange an old GPU, CPU or RAM against a product in stock. The operator
-- values each trade-in by hand from the proof the customer sends; the agreed value comes off the order.

-- Which products accept a trade-in, and the most the operator would give against each. The cap is
-- internal: like cost_lek it never reaches a public page.
ALTER TABLE product ADD COLUMN trade_eligible BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE product ADD COLUMN max_trade_value_lek INT;

CREATE TABLE trade_request (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_number          VARCHAR(20)   NOT NULL UNIQUE,
    product_id              BIGINT,
    product_title_snapshot  VARCHAR(200)  NOT NULL,
    customer_name           VARCHAR(120)  NOT NULL,
    contact_method          VARCHAR(10)   NOT NULL,
    customer_phone          VARCHAR(30),
    customer_email          VARCHAR(160),
    item_type               VARCHAR(10)   NOT NULL,
    manufacturer            VARCHAR(80)   NOT NULL,
    model                   VARCHAR(120)  NOT NULL,
    extra_notes             VARCHAR(1000),
    -- stored_file key of the proof video or image; cleared when the media is deleted after closing
    media_filename          VARCHAR(200),
    media_type              VARCHAR(10),
    whatsapp_instead        BOOLEAN       NOT NULL DEFAULT FALSE,
    status                  VARCHAR(20)   NOT NULL,
    quoted_value_lek        INT,
    quote_notes             VARCHAR(1000),
    decline_reason          VARCHAR(1000),
    quoted_at               TIMESTAMP,
    quote_expires_at        TIMESTAMP,
    quote_emailed_at        TIMESTAMP,
    closed_at               TIMESTAMP,
    created_at              TIMESTAMP     NOT NULL,
    order_id                BIGINT,
    -- the Draft product created from the traded-in item, once it is taken into stock
    stock_product_id        BIGINT,
    CONSTRAINT fk_trade_product FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE SET NULL,
    CONSTRAINT fk_trade_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE SET NULL,
    CONSTRAINT fk_trade_stock FOREIGN KEY (stock_product_id) REFERENCES product (id) ON DELETE SET NULL
);

CREATE INDEX ix_trade_status ON trade_request (status, created_at);
CREATE INDEX ix_trade_product ON trade_request (product_id);
CREATE INDEX ix_trade_order ON trade_request (order_id);
CREATE INDEX ix_trade_stock ON trade_request (stock_product_id);

-- Per-year counter behind TR-2026-0001, separate from the order numbers.
CREATE TABLE trade_sequence (
    seq_year  INT PRIMARY KEY,
    last_no   INT NOT NULL
);

-- An order made from an accepted trade-in: the agreed value comes off the total.
ALTER TABLE orders ADD COLUMN trade_request_id BIGINT;
ALTER TABLE orders ADD COLUMN trade_credit_lek INT NOT NULL DEFAULT 0;
ALTER TABLE orders ADD CONSTRAINT fk_order_trade FOREIGN KEY (trade_request_id) REFERENCES trade_request (id) ON DELETE SET NULL;
CREATE INDEX ix_orders_trade ON orders (trade_request_id);

-- Like every table (see V6__supabase_hardening.sql).
ALTER TABLE trade_request ENABLE ROW LEVEL SECURITY;
ALTER TABLE trade_sequence ENABLE ROW LEVEL SECURITY;
