-- The GPU catalogue: one row per graphics card model, with the reference data the assistant reasons
-- over (VRAM, power, tier, upscaling, driver status, typical frame rates). The rows come from
-- data/gpu-catalog.json, upserted on slug by the repeatable migration R__Seed_gpu_catalog, and can be
-- edited in Admin > Katalogu GPU. A product points at a row through product.gpu_model_id (the admin
-- autofill stamps it), so the assistant works from structured data instead of parsing titles.
CREATE TABLE gpu_catalog (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug                VARCHAR(80)   NOT NULL UNIQUE,
    name                VARCHAR(120)  NOT NULL,
    vendor              VARCHAR(10)   NOT NULL,
    -- comma-separated search terms, matched alongside the name
    aliases             VARCHAR(300),
    release_year        INT,
    architecture        VARCHAR(60),
    vram_gb             INT,
    memory_type         VARCHAR(20),
    memory_bus_bits     INT,
    tdp_watts           INT,
    psu_min_watts       INT,
    pcie_connectors     VARCHAR(40),
    -- reference length; partner (AIB) cards vary, the exact one goes in the product's specs
    length_mm           INT,
    -- 1-20 performance rank
    tier                INT,
    supports_dlss       VARCHAR(10),
    frame_generation    BOOLEAN       NOT NULL DEFAULT FALSE,
    supports_fsr        VARCHAR(10),
    ray_tracing         BOOLEAN       NOT NULL DEFAULT FALSE,
    driver_status       VARCHAR(10),
    mining_risk         VARCHAR(10),
    fps_esports_1080p   INT,
    fps_aaa_1080p       INT,
    fps_aaa_1440p       INT,
    notes_sq            VARCHAR(1000)
);

CREATE INDEX ix_gpu_catalog_tier ON gpu_catalog (tier);

ALTER TABLE product ADD COLUMN gpu_model_id BIGINT;
ALTER TABLE product ADD CONSTRAINT fk_product_gpu_model FOREIGN KEY (gpu_model_id) REFERENCES gpu_catalog (id) ON DELETE SET NULL;
CREATE INDEX ix_product_gpu_model ON product (gpu_model_id);

-- Like every table (see V6__supabase_hardening.sql).
ALTER TABLE gpu_catalog ENABLE ROW LEVEL SECURITY;
