-- The customer assistant: one row per conversation, its messages, the leads it captured, and the
-- running monthly API spend behind the cap that hides the widget.

CREATE TABLE chat_session (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- random token the browser keeps; the only handle a visitor has on their conversation
    session_token    VARCHAR(64)  NOT NULL UNIQUE,
    started_at       TIMESTAMP    NOT NULL,
    last_message_at  TIMESTAMP    NOT NULL,
    -- customer messages so far: the 25-message guardrail counts these
    message_count    INT          NOT NULL DEFAULT 0,
    lead_captured    BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE INDEX ix_chat_session_last ON chat_session (last_message_at);

CREATE TABLE chat_message (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id      BIGINT       NOT NULL,
    role            VARCHAR(10)  NOT NULL,
    content         TEXT         NOT NULL,
    -- the tools the assistant called for this reply and the product slugs they surfaced, as JSON
    tool_calls_json TEXT,
    created_at      TIMESTAMP    NOT NULL,
    CONSTRAINT fk_chat_message_session FOREIGN KEY (session_id) REFERENCES chat_session (id) ON DELETE CASCADE
);

CREATE INDEX ix_chat_message_session ON chat_message (session_id, id);

CREATE TABLE chat_lead (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id    BIGINT        NOT NULL,
    name          VARCHAR(120)  NOT NULL,
    phone         VARCHAR(30)   NOT NULL,
    wanted_item   VARCHAR(200)  NOT NULL,
    budget_lek    INT,
    psu_watts     INT,
    notes         VARCHAR(1000),
    status        VARCHAR(20)   NOT NULL,
    created_at    TIMESTAMP     NOT NULL,
    CONSTRAINT fk_chat_lead_session FOREIGN KEY (session_id) REFERENCES chat_session (id) ON DELETE CASCADE
);

CREATE INDEX ix_chat_lead_status ON chat_lead (status, created_at);
CREATE INDEX ix_chat_lead_session ON chat_lead (session_id);

-- One row per calendar month: what the assistant has cost so far, in millionths of a dollar so the
-- arithmetic stays in integers. Read before every reply against the configured monthly cap.
CREATE TABLE chat_usage (
    month               VARCHAR(7)  PRIMARY KEY,
    input_tokens        BIGINT      NOT NULL DEFAULT 0,
    output_tokens       BIGINT      NOT NULL DEFAULT 0,
    cache_read_tokens   BIGINT      NOT NULL DEFAULT 0,
    cache_write_tokens  BIGINT      NOT NULL DEFAULT 0,
    cost_micro_usd      BIGINT      NOT NULL DEFAULT 0,
    replies             INT         NOT NULL DEFAULT 0,
    updated_at          TIMESTAMP   NOT NULL
);

-- Like every table (see V6__supabase_hardening.sql): customers' names and phone numbers live here.
ALTER TABLE chat_session ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_message ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_lead    ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_usage   ENABLE ROW LEVEL SECURITY;
