-- The assistant is provider-agnostic: Gemini now, Anthropic later, a deterministic "guided finder"
-- as the floor. Each conversation and turn records who answered, leads may come from the chat's
-- contact form, the finder or a plain form, and provider_usage counts requests per day against the
-- providers' free-tier limits.

ALTER TABLE chat_session ADD COLUMN provider_used VARCHAR(20);
ALTER TABLE chat_message ADD COLUMN provider_used VARCHAR(20);

-- A lead no longer needs a conversation behind it (the finder and the plain form have none), and the
-- customer's details never pass through a model: they are posted straight to /api/lead by the site.
ALTER TABLE chat_lead ALTER COLUMN session_id DROP NOT NULL;
ALTER TABLE chat_lead ADD COLUMN source VARCHAR(10) NOT NULL DEFAULT 'CHAT';

CREATE TABLE provider_usage (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider         VARCHAR(30)  NOT NULL,
    day              DATE         NOT NULL,
    request_count    INT          NOT NULL DEFAULT 0,
    error_count      INT          NOT NULL DEFAULT 0,
    rate_limit_hits  INT          NOT NULL DEFAULT 0,
    CONSTRAINT uq_provider_usage UNIQUE (provider, day)
);

-- Like every table (see V6__supabase_hardening.sql).
ALTER TABLE provider_usage ENABLE ROW LEVEL SECURITY;
