CREATE TABLE category (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_sq     VARCHAR(100) NOT NULL,
    slug        VARCHAR(100) NOT NULL UNIQUE,
    sort_order  INT          NOT NULL DEFAULT 0,
    icon_class  VARCHAR(60)
);

CREATE TABLE brand (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(80) NOT NULL UNIQUE,
    slug  VARCHAR(80) NOT NULL UNIQUE
);

CREATE TABLE product (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title               VARCHAR(200) NOT NULL,
    brand_id            BIGINT,
    model               VARCHAR(120),
    category_slug       VARCHAR(100) NOT NULL,
    slug                VARCHAR(220) NOT NULL UNIQUE,
    item_condition      VARCHAR(20)  NOT NULL,
    price_lek           INT          NOT NULL,
    cost_lek            INT          NOT NULL DEFAULT 0,
    quantity            INT          NOT NULL DEFAULT 1,
    status              VARCHAR(20)  NOT NULL,
    short_description   VARCHAR(500),
    full_description    TEXT,
    warranty_days       INT,
    test_notes          TEXT,
    is_mining_free      BOOLEAN      NOT NULL DEFAULT FALSE,
    transport_included  BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMP    NOT NULL,
    listed_at           TIMESTAMP,
    sold_at             TIMESTAMP,
    view_count          INT          NOT NULL DEFAULT 0,
    CONSTRAINT fk_product_brand FOREIGN KEY (brand_id) REFERENCES brand (id),
    CONSTRAINT fk_product_category FOREIGN KEY (category_slug) REFERENCES category (slug) ON UPDATE CASCADE
);

CREATE INDEX ix_product_status_listed ON product (status, listed_at);
CREATE INDEX ix_product_category_status ON product (category_slug, status);
CREATE INDEX ix_product_price ON product (price_lek);

CREATE TABLE product_spec (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT       NOT NULL,
    spec_key    VARCHAR(80)  NOT NULL,
    spec_value  VARCHAR(160) NOT NULL,
    sort_order  INT          NOT NULL DEFAULT 0,
    CONSTRAINT fk_spec_product FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE
);

CREATE INDEX ix_spec_key_value ON product_spec (spec_key, spec_value);

CREATE TABLE product_image (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT       NOT NULL,
    filename    VARCHAR(100) NOT NULL,
    sort_order  INT          NOT NULL DEFAULT 0,
    is_primary  BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_image_product FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE
);

CREATE TABLE orders (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number     VARCHAR(20)  NOT NULL UNIQUE,
    customer_name    VARCHAR(120) NOT NULL,
    customer_phone   VARCHAR(30)  NOT NULL,
    customer_email   VARCHAR(160),
    city             VARCHAR(80)  NOT NULL,
    address          VARCHAR(255),
    customer_notes   VARCHAR(1000),
    delivery_method  VARCHAR(20)  NOT NULL,
    payment_method   VARCHAR(20)  NOT NULL,
    status           VARCHAR(20)  NOT NULL,
    subtotal_lek     INT          NOT NULL,
    shipping_lek     INT          NOT NULL,
    total_lek        INT          NOT NULL,
    admin_notes      TEXT,
    created_at       TIMESTAMP    NOT NULL,
    delivered_at     TIMESTAMP
);

CREATE INDEX ix_orders_status ON orders (status, created_at);

CREATE TABLE order_item (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id             BIGINT       NOT NULL,
    product_id           BIGINT,
    title_snapshot       VARCHAR(200) NOT NULL,
    price_lek_snapshot   INT          NOT NULL,
    cost_lek_snapshot    INT          NOT NULL,
    quantity             INT          NOT NULL,
    CONSTRAINT fk_item_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
    CONSTRAINT fk_item_product FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE SET NULL
);

-- Per-year counter backing human-readable order numbers (PM-2026-0001)
CREATE TABLE order_sequence (
    seq_year  INT PRIMARY KEY,
    last_no   INT NOT NULL
);

CREATE TABLE build_request (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name     VARCHAR(120) NOT NULL,
    customer_phone    VARCHAR(30)  NOT NULL,
    budget_lek        INT          NOT NULL,
    use_case          VARCHAR(20)  NOT NULL,
    notes             TEXT,
    status            VARCHAR(20)  NOT NULL,
    quoted_total_lek  INT,
    admin_notes       TEXT,
    created_at        TIMESTAMP    NOT NULL
);

CREATE INDEX ix_build_status ON build_request (status, created_at);

CREATE TABLE admin_user (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username       VARCHAR(60)  NOT NULL UNIQUE,
    password_hash  VARCHAR(100) NOT NULL,
    enabled        BOOLEAN      NOT NULL DEFAULT TRUE
);
