-- Uploaded files live in the database rather than on disk.
--
-- The hosted service has no persistent filesystem: every deploy starts from the container image,
-- so anything written to disk is lost. Keeping the bytes here means product photos survive a
-- deploy, and it needs no second service and no additional API key to protect.
--
-- file_key doubles as the path the file is served at, e.g. "img/thumb/<uuid>.jpg" or
-- "app/pcmania-admin.apk", which is why it is unique.
CREATE TABLE stored_file (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_key      VARCHAR(200) NOT NULL UNIQUE,
    content_type  VARCHAR(100) NOT NULL,
    size_bytes    INT          NOT NULL,
    -- Pixel size is recorded at upload so Open Graph tags do not have to re-read the image.
    width_px      INT,
    height_px     INT,
    -- Free text shown in the admin screen, e.g. the original filename of an uploaded APK.
    label         VARCHAR(200),
    data          BYTEA        NOT NULL,
    created_at    TIMESTAMP    NOT NULL
);

ALTER TABLE stored_file ENABLE ROW LEVEL SECURITY;
