-- "Kërko një produkt": what customers ask the shop to bring in. The operator works through them from
-- Admin > Lista e dëshirave and calls the customer back once the item is found.
CREATE TABLE wish_request (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name   VARCHAR(120)  NOT NULL,
    customer_phone  VARCHAR(30)   NOT NULL,
    item            VARCHAR(200)  NOT NULL,
    max_price_lek   INT,
    item_condition  VARCHAR(20),
    notes           VARCHAR(1000),
    status          VARCHAR(20)   NOT NULL,
    admin_notes     TEXT,
    created_at      TIMESTAMP     NOT NULL
);

CREATE INDEX ix_wish_status ON wish_request (status, created_at);

-- Like every table: RLS on with no policies, so Supabase's public API can never read customers'
-- names and phone numbers from it (see V6__supabase_hardening.sql).
ALTER TABLE wish_request ENABLE ROW LEVEL SECURITY;
